### ISSUE TITLE
Could please help to solve this problem? 

### ISSUE THREAD

**Issue by MrBenzWorld** [simulkade/JFVM.jl#10]
![equation](https://user-images.githubusercontent.com/113277019/208853305-c1058f29-1331-41a7-8979-3ac3392aed4e.jpg)
![PT1](https://user-images.githubusercontent.com/113277019/208853313-09d371af-8582-4201-8c60-5d594dc6e706.jpg)

Could you please help to solve it in Julia ?
I can do it in ansys fluent , but I want learn Julia.

oscillating flow through pipe (2D)
it is a transient compressible, viscous 2D flow problem. also, conventional heat transfer considers from the pipe wall.
it is a convention diffusion problem. at both ends, there are porous heat exchangers.

Thank you

**Comment by simulkade** [comment]
Hi @MrBenzWorld, 
I can on only help with fixing bugs and adding new features.
