### ISSUE TITLE
Julia wrapper for SU2 (The Open-Source CFD Code) (Stanford University Unstructured)

### ISSUE THREAD

**Issue by MrBenzWorld** [simulkade/JFVM.jl#11]
Python wrapper is available for SU2 (The Open-Source CFD Code).
Please provide Julia wrapper for SU2.
SU2 is a suite of open-source software tools written in C++ for the numerical solution of partial differential equations and performing PDE-constrained optimization.

There is no package for CFD in Julia. SU2 is good access for Julia.

could you forward it to the correct group to get more attention?

**Comment by simulkade** [comment]
Thanks for pointing out the SU2 package. CFD simulations are not a priority for me but hopefully someone will develop a wrapper for SU2. In the meantime, there are a number of PDE solvers in pure Julia that you can find on github.
