### ISSUE TITLE
A question on 1D transient-diffusion problem

### ISSUE THREAD

**Issue by Beniuy** [simulkade/JFVM.jl#12]
In fliud flow, is this method still appropriate for curve path? That is to say , if the one-dimensional mesh is polyline, is the transient-diffusion still applicable? My purpose is studying the water pressure of the polyline/curve crack path,like the black simplified crack paths in the picture. I want to know whether I can treat the polyline as a straight line to solve the transient-diffusion problem?

**Comment by simulkade** [comment]
I'm not familiar with this problem. However, if you can describe the flux along the polyline with a diffusion equation, you should be able to solve it with JFVM. You need to do the conversion manually from your domain to the 1D Cartesian mesh of JFVM.

**Comment by Beniuy** [comment]
Thank you for resolving my question ！
