### ISSUE TITLE
A question about transient term calculation

### ISSUE THREAD

**Issue by Beniuy** [simulkade/JFVM.jl#13]
What is the significance of using dt step-by-step calculation in transient term calculation? Will using a one-step calculation result in significant errors (compared to step-by-step calculation) ?

Thanks a lot for your help !

**Comment by simulkade** [comment]
It depends on your, PDE, grid size, and of course step-size :-). Have a look at the PDE and ODE numerical solvers.

**Comment by Beniuy** [comment]
Okay, thank you for your helpful answer. :-)
