### ISSUE TITLE
Cylindrical1D version of Nonlinear PDE example

### ISSUE THREAD

**Issue by dharp** [simulkade/JFVM.jl#6]
I am trying to convert the Nonlinear PDE example (https://nbviewer.jupyter.org/github/simulkade/JFVM.jl/blob/master/examples/solving-nonlinear-pdes-with-fvm.ipynb) to a Cylindrical1D mesh. The left (r=0) boundary is the standard (a=1,b=0,c=0) while the right boundary is a Robin BC. It appears that the Robin BC is working, but the left boundary holds the value (acts like a Dirichlet boundary) instead of allowing phi to drop. Perhaps I'm missing something in the conversion? The script is attached here:
[FV_polygon1Dradial.jl.zip](https://github.com/simulkade/JFVM.jl/files/4435492/FV_polygon1Dradial.jl.zip)

The output of the script looks like:
![Figure_1](https://user-images.githubusercontent.com/2457348/78516247-24795880-7776-11ea-8b01-9f654731d8f4.png)

But should look something more like:
![compare](https://user-images.githubusercontent.com/2457348/78516411-af5a5300-7776-11ea-8b0e-22632890f214.png)

**Comment by simulkade** [comment]
Hi Dylan,

Your script looks fine. Judging by the figures you have attached, it seems
to me that the left boundary has not "sensed" the changes that are
occurring due to the Robin condition at the right boundary. Have you tried
increasing the time step?

Ali

**Comment by simulkade** [comment]
This is what I got by increasing Kr to 50.0:
![image](https://user-images.githubusercontent.com/1881542/78591102-35dc6680-7843-11ea-9c7e-a65c6694f132.png)

**Comment by dharp** [comment]
Thank you for taking a look at this. Yes, you are exactly right. Everything seems to be working now.

Thanks,
Dylan

**Comment by simulkade** [comment]
No problem, Dylan. Feel free to open new issues if you run into problem. I've been very lazy documenting this code.
